_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 41
                - 49
                - 55
                - 63
                - 80
                - 105
            "2":
                - 1
                - 41
                - 49
                - 55
                - 63
                - 80
                - 105
            "3":
                - 2
                - 13
                - 15
                - 16
                - 23
                - 55
            "4": 3.12.7
            "5": 0.18.7
            "8":
                - 1
                - 5
            "12": 0.18.7
            "13": linux-x86_64
architecture:
    value: efficientnetv2_rw_t.ra2_in1k_4_augmented
batch_size:
    value: 32
criterion:
    value: CrossEntropyLoss
learning_rate:
    value: 0.0003
num_classes:
    value: 47
num_epochs:
    value: 50
optimizer:
    value: Adam
